# -*- coding: utf-8 -*-
"""
/***************************************************************************
 gridUtm
                                 A QGIS plugin
 grid with utm
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-21
        copyright            : (C) 2021 by Bienvenue
        email                : bienvenue@tag-ip.xyz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load gridUtm class from file gridUtm.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gridutm import gridUtm
    return gridUtm(iface)
